name: docs

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'

defaults:
  run:
    working-directory: ./docs

jobs:

  publish:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/heads/master')
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Publish to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.ABENEVAUT_GITHUB_TOKEN }}
